[package]
name = "rest-model"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
anyhow = "1.0.89"
chrono = "0.4"
rest-model-macro = { path = "../rest-model-macro" }
